### ISSUE TITLE
Grib 2 Json converter

### ISSUE THREAD

**Issue by Jamos1988** [panaaj/freeboard-sk-helper#1]
I'd like to know for the experimental feature, what the best way is to obtain the Grib Json files is.
I've found this one https://github.com/weacast/weacast-grib2json but If you have a preferred method I'd rather use that of course.

**Comment by Jamos1988** [comment]
Edit: I see that you already use a tool and I need a Grib2 file, place it into the grib folder. I'll check if Xygrib delivers Grib2 files, because in Freeboard I couldn't select the gribfile from the dropdown.

**Comment by Jamos1988** [comment]
Ok, I verify that xygrib generates .grb2 files, placed it into the grib folder, but the experimental feature does not see the file as I cannot select it in the dropdown.

**Comment by panaaj** [comment]
The files need to JSON files in the format created by the GRIB2JSON tool.

**Comment by Jamos1988** [comment]
Thx! I am having trouble finding / using the tool, is it this one?

https://www.npmjs.com/package/grib2json

I've read the instruction, but I can't seem to understand how I would get started easily. Are there a few "easy" to follow terminal commands I can execute, or do I need to build scripts?

Hope you can point me in the right direction.

**Comment by panaaj** [comment]
https://nicedoc.io/cambecc/grib2json

**Comment by Jamos1988** [comment]
Thx, I've done the installation, but stuck with the usage part:

The grib2json launch script is located in the bin directory and requires the JAVA_HOME environment variable to be defined.

I run sudo nano editing the grib2json launch script, but not sure where to add the java_home variable (path?)

**Comment by panaaj** [comment]
Environment variables are often set in your .profile or you can set it from the command line.

**Comment by Jamos1988** [comment]
I have never worked with environment variables, so don't know how to do it. I've found the folder /etc/profile.d
but after that I don't know what to do.

**Comment by panaaj** [comment]
The following
[link](https://www.edureka.co/community/47597/setting-java-home-in-linux)  may help.

**Comment by Jamos1988** [comment]
thx, i've set the variable, now when running the following I get the command not found:

`pi@openplotter:~/grib2json/src/bin $ grib2json --help
bash: grib2json: command not found
`

**Comment by panaaj** [comment]
Please review the GRIB2JSON documentation.
`freeboard-sk-helper` does not invoke or require GRIB2JSON to operate, it does however process wind and temperature data within the JSON files GRIB2JSON produces.
As your issue seems to be with GRIB2JSON operation I would suggest that this issue be closed as it does not relate to an issue with `freeboard-sk-helper` operation.
