### ISSUE TITLE
Tracks Experimental Function

### ISSUE THREAD

**Issue by pchambers** [panaaj/freeboard-sk-helper#2]
Currently trying to test the Tracks Experiment on Freeboard in the earliest. I added a geoJson MultiLineString in the .signalk/freeboard-sk-helper/tracks directory, I consistently receive a syntax error in the SignalK server logs when selecting 'Tracks' on the Freeboard dropdown experiments. 

Server Log: 
Sep 01 15:13:46 SyntaxError: Unexpected token _awaiter (/home/pi/.signalk/node_modules/freeboard-sk-helper/plugin/lib/trackfiles.js:4:12) at TrackStore.getResources (/home/pi/.signalk/node_modules/freeboard-sk-helper/plugin/lib/trackfiles.js:69:16) at /home/pi/.signalk/node_modules/freeboard-sk-helper/plugin/index.js:240:38 at Generator.next (<anonymous>) at /home/pi/.signalk/node_modules/freeboard-sk-helper/plugin/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/home/pi/.signalk/node_modules/freeboard-sk-helper/plugin/index.js:4:12) at router.get (/home/pi/.signalk/node_modules/freeboard-sk-helper/plugin/index.js:238:55) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:137:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:281:22 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:335:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:275:10) 
Sep 01 15:13:46 GET /signalk/v1/api/resources/tracks 304 9.623 ms - - 

and the Browser Console error: 

main-es2015.13cf90c4bad9a2812e6e.js:1 ERROR TypeError: Cannot set property 'id' of undefined
    at main-es2015.13cf90c4bad9a2812e6e.js:1
    at Array.map (<anonymous>)
    at c.sk.api.get.subscribe.trackList [as _next] (main-es2015.13cf90c4bad9a2812e6e.js:1)
    at c.__tryOrUnsub (main-es2015.13cf90c4bad9a2812e6e.js:1)
    at c.next (main-es2015.13cf90c4bad9a2812e6e.js:1)
    at u._next (main-es2015.13cf90c4bad9a2812e6e.js:1)
    at u.next (main-es2015.13cf90c4bad9a2812e6e.js:1)
    at s._next (main-es2015.13cf90c4bad9a2812e6e.js:1)
    at s.next (main-es2015.13cf90c4bad9a2812e6e.js:1)
    at s._next (main-es2015.13cf90c4bad9a2812e6e.js:1)
ce @ main-es2015.13cf90c4bad9a2812e6e.js:1
handleError @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
i @ main-es2015.13cf90c4bad9a2812e6e.js:1
__tryOrUnsub @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
_next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
emit @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
e.invoke @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.run @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
runOutsideAngular @ main-es2015.13cf90c4bad9a2812e6e.js:1
onHandleError @ main-es2015.13cf90c4bad9a2812e6e.js:1
e.handleError @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.runTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.invokeTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
invoke @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
n.args.<computed> @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
setTimeout (async)
c @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
e.scheduleTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
onScheduleTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
e.scheduleTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.scheduleTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.scheduleMacroTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
d @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
(anonymous) @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
R.a.<computed> @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
i @ main-es2015.13cf90c4bad9a2812e6e.js:1
__tryOrUnsub @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
_next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
_next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
_next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
notifyNext @ main-es2015.13cf90c4bad9a2812e6e.js:1
_next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
s @ main-es2015.13cf90c4bad9a2812e6e.js:1
e.invokeTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
onInvokeTask @ main-es2015.13cf90c4bad9a2812e6e.js:1
e.invokeTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.runTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.invokeTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
_ @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
m @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
load (async)
C @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
e.scheduleTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
onScheduleTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
e.scheduleTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.scheduleTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.scheduleEventTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
(anonymous) @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
_trySubscribe @ main-es2015.13cf90c4bad9a2812e6e.js:1
subscribe @ main-es2015.13cf90c4bad9a2812e6e.js:1
s @ main-es2015.13cf90c4bad9a2812e6e.js:1
_innerSub @ main-es2015.13cf90c4bad9a2812e6e.js:1
_tryNext @ main-es2015.13cf90c4bad9a2812e6e.js:1
_next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
_trySubscribe @ main-es2015.13cf90c4bad9a2812e6e.js:1
subscribe @ main-es2015.13cf90c4bad9a2812e6e.js:1
call @ main-es2015.13cf90c4bad9a2812e6e.js:1
subscribe @ main-es2015.13cf90c4bad9a2812e6e.js:1
call @ main-es2015.13cf90c4bad9a2812e6e.js:1
subscribe @ main-es2015.13cf90c4bad9a2812e6e.js:1
call @ main-es2015.13cf90c4bad9a2812e6e.js:1
subscribe @ main-es2015.13cf90c4bad9a2812e6e.js:1
getTracks @ main-es2015.13cf90c4bad9a2812e6e.js:1
ngOnInit @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
vr @ main-es2015.13cf90c4bad9a2812e6e.js:1
Wr @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
updateDirectives @ main-es2015.13cf90c4bad9a2812e6e.js:1
yr @ main-es2015.13cf90c4bad9a2812e6e.js:1
Tr @ main-es2015.13cf90c4bad9a2812e6e.js:1
Ir @ main-es2015.13cf90c4bad9a2812e6e.js:1
yr @ main-es2015.13cf90c4bad9a2812e6e.js:1
detectChanges @ main-es2015.13cf90c4bad9a2812e6e.js:1
enter @ main-es2015.13cf90c4bad9a2812e6e.js:1
open @ main-es2015.13cf90c4bad9a2812e6e.js:1
openExperiment @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
handleEvent @ main-es2015.13cf90c4bad9a2812e6e.js:1
handleEvent @ main-es2015.13cf90c4bad9a2812e6e.js:1
tl @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
i @ main-es2015.13cf90c4bad9a2812e6e.js:1
__tryOrUnsub @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
_next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
next @ main-es2015.13cf90c4bad9a2812e6e.js:1
emit @ main-es2015.13cf90c4bad9a2812e6e.js:1
handleSelect @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
handleEvent @ main-es2015.13cf90c4bad9a2812e6e.js:1
handleEvent @ main-es2015.13cf90c4bad9a2812e6e.js:1
tl @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
(anonymous) @ main-es2015.13cf90c4bad9a2812e6e.js:1
e.invokeTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
onInvokeTask @ main-es2015.13cf90c4bad9a2812e6e.js:1
e.invokeTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.runTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
t.invokeTask @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
_ @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
m @ polyfills-es2015.b1b1e7a19d89acae1cf2.js:1
Show 66 more frames

**Comment by panaaj** [comment]
It sounds like the file is not of the expected format.
The experiment is intended for use via the GPX Import function in Freeboard so therefore the files placed in the folder are formatted correctly.

The content of the file is aligned with other Signal K resource type definitions so the GeoJSON is placed within a "feature" property. So the contents of a valid file will look like this:
```
{
     "feature": {
          "type": "Feature",
          "geometry": { 
                  "type": "MultiLineString",
                  "coordinates": [...]
          }
          "properties": { ... }
     }
}
```

**Comment by panaaj** [comment]
v1.1.1 adds additional validation to address "manual file addition"

**Comment by pchambers** [comment]
That was it, thanks!
